name: my_app
description: A New Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  cache_client:
    path: packages/cache_client
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  get_it: ^7.6.4
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  generate: true
